# Generated by Django 5.1.2 on 2026-02-25 22:19

import django.db.models.deletion
import secured_fields.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historicalappointment_historicalclinic_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='brand_color',
            field=models.CharField(default='#1d4ed8', max_length=7),
        ),
        migrations.AddField(
            model_name='clinic',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='confirmation_code',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='historicalclinic',
            name='brand_color',
            field=models.CharField(default='#1d4ed8', max_length=7),
        ),
        migrations.AddField(
            model_name='historicalclinic',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='email',
            field=secured_fields.fields.EncryptedCharField(max_length=254, searchable=True),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='phone',
            field=secured_fields.fields.EncryptedCharField(max_length=32, searchable=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=secured_fields.fields.EncryptedCharField(max_length=254, searchable=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=secured_fields.fields.EncryptedCharField(max_length=32, searchable=True),
        ),
        migrations.CreateModel(
            name='AppointmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('price_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_types', to='core.clinic')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('clinic', 'name')},
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='core.appointmenttype'),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='appointment_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.appointmenttype'),
        ),
        migrations.CreateModel(
            name='HistoricalAppointmentType',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('price_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('clinic', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.clinic')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical appointment type',
                'verbose_name_plural': 'historical appointment types',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
