# Generated by Django 5.1.2 on 2026-02-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_plan_historicalplan_historicalclinicsubscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalplan',
            name='paypal_plan_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='paypal_plan_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
