# Generated by Django 5.1.2 on 2026-02-26 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_historicalpatient_user'),
        ('core', '0007_staff_patient_avatar'),
    ]

    operations = [
    ]
