# Generated by Django 5.1.2 on 2026-02-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20260227_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='avatar',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalstaff',
            name='avatar',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
