# Generated by Django 5.1.2 on 2026-03-04

from django.db import migrations
import secured_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_historicalpatient_avatar_historicalstaff_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancel_reason',
            field=secured_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='cancel_reason',
            field=secured_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
