# Generated by Django 5.1.2 on 2026-03-06 00:00

from django.db import migrations, models
from django.db.models import Q
from django.utils.text import slugify


def _build_unique_slug(name: str, existing: set[str]) -> str:
    base = slugify(name) or 'clinic'
    slug = base[:200]
    counter = 2
    while slug in existing:
        suffix = f'-{counter}'
        slug = f'{base[:200 - len(suffix)]}{suffix}'
        counter += 1
    existing.add(slug)
    return slug


def populate_clinic_slugs(apps, schema_editor):
    Clinic = apps.get_model('core', 'Clinic')
    existing = set(
        Clinic.objects.exclude(slug__isnull=True)
        .exclude(slug='')
        .values_list('slug', flat=True)
    )

    for clinic in Clinic.objects.filter(Q(slug__isnull=True) | Q(slug='')).order_by('id'):
        clinic.slug = _build_unique_slug(clinic.name, existing)
        clinic.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_appointment_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='historicalclinic',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(populate_clinic_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='clinic',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
