# Generated by Django 5.1.2 on 2026-03-06 00:00

from django.db import migrations, models
from django.db.models import Q
from django.utils.text import slugify


def populate_historicalclinic_slug(apps, schema_editor):
    Clinic = apps.get_model('core', 'Clinic')
    HistoricalClinic = apps.get_model('core', 'HistoricalClinic')

    slug_by_id = {clinic.id: clinic.slug for clinic in Clinic.objects.all()}

    qs = HistoricalClinic.objects.filter(Q(slug__isnull=True) | Q(slug=''))
    for record in qs.iterator():
        slug = slug_by_id.get(record.id)
        if not slug:
            slug = slugify(record.name) or 'clinic'
        record.slug = slug
        record.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_clinic_slug'),
    ]

    operations = [
        migrations.RunPython(populate_historicalclinic_slug, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='historicalclinic',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
