# Generated by Django 5.1.2 on 2026-03-23 10:11

from django.db import migrations, models


def seed_free_plan(apps, schema_editor):
    Plan = apps.get_model('core', 'Plan')

    free_plan = (
        Plan.objects.filter(is_free=True).order_by('id').first()
        or Plan.objects.filter(name__iexact='Free').order_by('id').first()
        or Plan.objects.filter(price_cents=0, paypal_plan_id__isnull=True).order_by('id').first()
    )

    plan_defaults = {
        'name': 'Free',
        'is_free': True,
        'paypal_plan_id': None,
        'price_cents': 0,
        'currency': 'USD',
        'interval': 'month',
        'staff_limit': 2,
        'service_limit': 3,
        'monthly_appointment_limit': 50,
        'includes_reminders': False,
        'includes_notifications': True,
        'includes_custom_branding': False,
        'is_active': True,
    }

    if free_plan:
        for field_name, value in plan_defaults.items():
            setattr(free_plan, field_name, value)
        free_plan.save(update_fields=list(plan_defaults.keys()))
        return

    Plan.objects.create(**plan_defaults)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplan',
            name='includes_custom_branding',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalplan',
            name='includes_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalplan',
            name='includes_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalplan',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalplan',
            name='monthly_appointment_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalplan',
            name='service_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalplan',
            name='staff_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='includes_custom_branding',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='includes_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='includes_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='monthly_appointment_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='service_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='staff_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(seed_free_plan, migrations.RunPython.noop),
    ]
