# Generated by Django 5.1.2 on 2026-03-31 18:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_securityevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('allow', 'Whitelist'), ('block', 'Block')], max_length=16)),
                ('target_type', models.CharField(choices=[('ip', 'IP or CIDR'), ('country', 'Country code')], max_length=16)),
                ('scope', models.CharField(choices=[('auth', 'Auth-sensitive routes'), ('global', 'Whole site')], default='auth', max_length=16)),
                ('value', models.CharField(max_length=64)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['action', 'target_type', 'value'],
            },
        ),
        migrations.AddField(
            model_name='securityevent',
            name='country_code',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login success'), ('login_failed', 'Login failed'), ('logout', 'Logout'), ('password_changed', 'Password changed'), ('rate_limited', 'Rate limited'), ('access_blocked', 'Access blocked')], max_length=64),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['country_code', '-created_at'], name='core_securi_country_d45abb_idx'),
        ),
        migrations.AddIndex(
            model_name='securityaccessrule',
            index=models.Index(fields=['is_active', 'action', 'target_type'], name='core_securi_is_acti_620b63_idx'),
        ),
        migrations.AddIndex(
            model_name='securityaccessrule',
            index=models.Index(fields=['scope', 'is_active'], name='core_securi_scope_ba463c_idx'),
        ),
        migrations.AddConstraint(
            model_name='securityaccessrule',
            constraint=models.UniqueConstraint(fields=('action', 'target_type', 'scope', 'value'), name='unique_security_access_rule'),
        ),
    ]
