# Generated by Django 5.1.2 on 2026-03-31 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_securityaccessrule_securityevent_country_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityevent',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login success'), ('login_failed', 'Login failed'), ('logout', 'Logout'), ('password_changed', 'Password changed'), ('rate_limited', 'Rate limited'), ('access_blocked', 'Access blocked'), ('two_factor_enabled', 'Two-factor enabled'), ('two_factor_disabled', 'Two-factor disabled'), ('two_factor_challenge_passed', 'Two-factor challenge passed'), ('two_factor_challenge_failed', 'Two-factor challenge failed'), ('two_factor_recovery_used', 'Two-factor recovery used'), ('two_factor_reset', 'Two-factor reset')], max_length=64),
        ),
        migrations.CreateModel(
            name='TwoFactorRecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64)),
                ('code_suffix', models.CharField(max_length=6)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_recovery_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id', 'created_at', 'id'],
                'indexes': [models.Index(fields=['user', 'consumed_at'], name='core_twofac_user_id_c1c781_idx')],
            },
        ),
    ]
