# Generated by Django 5.1.2 on 2026-03-31 23:38

import django.db.models.deletion
import secured_fields.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_securityevent_event_type_twofactorrecoverycode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consent_signature_name',
            field=secured_fields.fields.EncryptedCharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='consent_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='consent_to_privacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='consent_to_treatment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='intake_details',
            field=secured_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='intake_reason',
            field=secured_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='consent_signature_name',
            field=secured_fields.fields.EncryptedCharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='consent_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='consent_to_privacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='consent_to_treatment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='intake_details',
            field=secured_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='intake_reason',
            field=secured_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalWaitlistEntry',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('first_name', secured_fields.fields.EncryptedCharField(max_length=100)),
                ('last_name', secured_fields.fields.EncryptedCharField(max_length=100)),
                ('email', secured_fields.fields.EncryptedCharField(max_length=254, searchable=True)),
                ('phone', secured_fields.fields.EncryptedCharField(max_length=32, searchable=True)),
                ('preferred_start_date', models.DateField(blank=True, null=True)),
                ('preferred_end_date', models.DateField(blank=True, null=True)),
                ('notes', secured_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('consent_to_contact', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('contacted', 'Contacted'), ('booked', 'Booked'), ('closed', 'Closed')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('appointment_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.appointmenttype')),
                ('clinic', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.clinic')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.patient')),
            ],
            options={
                'verbose_name': 'historical waitlist entry',
                'verbose_name_plural': 'historical waitlist entrys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', secured_fields.fields.EncryptedCharField(max_length=100)),
                ('last_name', secured_fields.fields.EncryptedCharField(max_length=100)),
                ('email', secured_fields.fields.EncryptedCharField(max_length=254, searchable=True)),
                ('phone', secured_fields.fields.EncryptedCharField(max_length=32, searchable=True)),
                ('preferred_start_date', models.DateField(blank=True, null=True)),
                ('preferred_end_date', models.DateField(blank=True, null=True)),
                ('notes', secured_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('consent_to_contact', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('contacted', 'Contacted'), ('booked', 'Booked'), ('closed', 'Closed')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='core.appointmenttype')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='core.clinic')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='core.patient')),
            ],
            options={
                'ordering': ['status', 'preferred_start_date', 'created_at'],
                'indexes': [models.Index(fields=['clinic', 'status', 'created_at'], name='core_waitli_clinic__878ba8_idx')],
            },
        ),
    ]
