# Generated by Django 5.1.2 on 2026-04-02 22:52

import django.db.models.deletion
import django.utils.timezone
import secured_fields.fields
from django.conf import settings
from django.db import migrations, models


def seed_clinic_owner_and_messaging_permissions(apps, schema_editor):
    Clinic = apps.get_model('core', 'Clinic')
    Staff = apps.get_model('core', 'Staff')
    ClinicMessagingPermission = apps.get_model('core', 'ClinicMessagingPermission')
    user_app_label, user_model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(user_app_label, user_model_name)

    default_access = {
        'Admin': 'reply',
        'Doctor': 'reply',
        'Nurse': 'view',
        'FrontDesk': 'reply',
    }

    for clinic in Clinic.objects.all():
        if clinic.owner_user_id is None:
            owner_user = (
                User.objects.filter(staff__clinic=clinic, groups__name='Admin')
                .order_by('staff__id')
                .first()
            )
            if owner_user is None:
                fallback_staff = Staff.objects.filter(clinic=clinic).order_by('id').first()
                owner_user = getattr(fallback_staff, 'user', None)
            if owner_user is not None:
                clinic.owner_user = owner_user
                clinic.save(update_fields=['owner_user'])

        for role, access_level in default_access.items():
            ClinicMessagingPermission.objects.get_or_create(
                clinic=clinic,
                role=role,
                defaults={'access_level': access_level},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_appointment_consent_signature_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='owner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_clinics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalclinic',
            name='owner_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=140)),
                ('source', models.CharField(choices=[('appointment', 'Appointment link'), ('portal', 'Patient portal')], default='portal', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=16)),
                ('last_message_sender_type', models.CharField(choices=[('patient', 'Patient'), ('staff', 'Staff'), ('system', 'System')], default='patient', max_length=16)),
                ('last_message_excerpt', models.CharField(blank=True, max_length=180)),
                ('last_message_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_threads', to='core.appointment')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_threads', to='core.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_threads', to='core.patient')),
            ],
            options={
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('patient', 'Patient'), ('staff', 'Staff'), ('system', 'System')], max_length=16)),
                ('sender_label', models.CharField(blank=True, max_length=150)),
                ('body', secured_fields.fields.EncryptedTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_thread_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.messagethread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageThreadReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='core.messagethread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_thread_read_states', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicMessagingPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('FrontDesk', 'Front Desk')], max_length=32)),
                ('access_level', models.CharField(choices=[('none', 'No access'), ('view', 'View only'), ('reply', 'View and reply')], default='none', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_permissions', to='core.clinic')),
            ],
            options={
                'ordering': ['role'],
                'constraints': [models.UniqueConstraint(fields=('clinic', 'role'), name='uniq_clinic_messaging_role')],
            },
        ),
        migrations.AddIndex(
            model_name='messagethread',
            index=models.Index(fields=['clinic', 'status', '-last_message_at'], name='core_messag_clinic__f8793c_idx'),
        ),
        migrations.AddIndex(
            model_name='messagethread',
            index=models.Index(fields=['patient', '-last_message_at'], name='core_messag_patient_078bf0_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagethread',
            constraint=models.UniqueConstraint(condition=models.Q(('appointment__isnull', False)), fields=('appointment',), name='uniq_message_thread_per_appointment'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread', 'created_at'], name='core_messag_thread__d04c3a_idx'),
        ),
        migrations.AddIndex(
            model_name='messagethreadreadstate',
            index=models.Index(fields=['user', 'last_read_at'], name='core_messag_user_id_36d873_idx'),
        ),
        migrations.AddConstraint(
            model_name='messagethreadreadstate',
            constraint=models.UniqueConstraint(fields=('thread', 'user'), name='uniq_thread_read_state'),
        ),
        migrations.RunPython(seed_clinic_owner_and_messaging_permissions, migrations.RunPython.noop),
    ]
