# Generated by Django 5.1.2 on 2026-04-04 05:26

import django.db.models.deletion
import secured_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_clinic_owner_user_historicalclinic_owner_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('support', 'Support request'), ('feature', 'Feature request')], max_length=16)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In review'), ('planned', 'Planned'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=16)),
                ('category', models.CharField(blank=True, max_length=32)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=16)),
                ('subject', models.CharField(max_length=140)),
                ('details', secured_fields.fields.EncryptedTextField()),
                ('business_impact', secured_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('page_url', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('reporter_name', models.CharField(blank=True, max_length=150)),
                ('reporter_email', models.EmailField(blank=True, max_length=254)),
                ('staff_role', models.CharField(blank=True, max_length=32)),
                ('internal_notes', secured_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to='core.clinic')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clinic', 'request_type', 'status', '-created_at'], name='core_helpre_clinic__505099_idx'), models.Index(fields=['submitted_by', '-created_at'], name='core_helpre_submitt_ce551b_idx')],
            },
        ),
    ]
