# Generated by Django 5.1.2 on 2026-04-04 17:40

from django.db import migrations, models


def seed_plan_feature_flags(apps, schema_editor):
    Plan = apps.get_model('core', 'Plan')
    HistoricalPlan = apps.get_model('core', 'HistoricalPlan')

    Plan.objects.filter(is_free=True).update(
        includes_messaging=False,
        includes_waitlist=False,
    )
    Plan.objects.filter(is_free=False).update(
        includes_messaging=True,
        includes_waitlist=True,
    )
    HistoricalPlan.objects.filter(is_free=True).update(
        includes_messaging=False,
        includes_waitlist=False,
    )
    HistoricalPlan.objects.filter(is_free=False).update(
        includes_messaging=True,
        includes_waitlist=True,
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_helprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplan',
            name='includes_messaging',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalplan',
            name='includes_waitlist',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='includes_messaging',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='includes_waitlist',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(seed_plan_feature_flags, noop_reverse),
    ]
