"""
Django settings for clinicops project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

BASE_DIR = Path(__file__).resolve().parent.parent

try:
    from dotenv import load_dotenv

    load_dotenv(BASE_DIR / '.env')
except Exception:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

DEFAULT_SECRET_KEY = 'django-insecure-0*w2i$(6=$93#uiufsulhsc*yaol)^s%tppm!3efrk%dy+s0f2'
DEFAULT_SECURED_FIELDS_KEY = 'TtY8MAeXuhdKDd1HfGUwim-vQ8H7fXyRQ9J8pTi_-lg='
DEFAULT_SECURED_FIELDS_HASH_SALT = 'dev-salt'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', DEFAULT_SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'true').lower() == 'true'

_allowed_hosts = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1')
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts.split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'admin_interface',
    'colorfield',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'simple_history',
    'secured_fields',
    'django_q',
    'core.apps.CoreConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'core.middleware.SecurityAccessMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'core.two_factor_middleware.TwoFactorEnforcementMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'clinicops.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.user_roles',
            ],
        },
    },
]

WSGI_APPLICATION = 'clinicops.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASE_URL = os.environ.get('DATABASE_URL')
USE_SQLITE = os.environ.get('USE_SQLITE', 'true').lower() == 'true'

if DATABASE_URL:
    DATABASES = {'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)}
elif USE_SQLITE:
    DATABASES = {'default': {'ENGINE': 'django.db.backends.sqlite3', 'NAME': BASE_DIR / 'db.sqlite3'}}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', 'clinicops'),
            'USER': os.environ.get('POSTGRES_USER', 'clinicops'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'clinicops'),
            'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

SITE_ID = 1


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_REDIRECT_URL = '/post-login/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

DJANGO_SECURE = os.environ.get('DJANGO_SECURE', 'false').lower() == 'true'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if DJANGO_SECURE else None
SECURE_SSL_REDIRECT = DJANGO_SECURE
SESSION_COOKIE_SECURE = DJANGO_SECURE
CSRF_COOKIE_SECURE = DJANGO_SECURE
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_SAMESITE = 'Lax'
SECURE_HSTS_SECONDS = 31536000 if DJANGO_SECURE else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = DJANGO_SECURE
SECURE_HSTS_PRELOAD = DJANGO_SECURE
SECURE_REFERRER_POLICY = 'same-origin'
SECURE_CONTENT_TYPE_NOSNIFF = True

CSRF_TRUSTED_ORIGINS = [
    origin
    for origin in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]

EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.smtp.EmailBackend',
)
EMAIL_HOST = os.environ.get('SMTP_HOST', 'localhost')
EMAIL_PORT = int(os.environ.get('SMTP_PORT', '1025'))
EMAIL_HOST_USER = os.environ.get('SMTP_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('SMTP_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('SMTP_USE_TLS', 'false').lower() == 'true'
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '10'))
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'ClinicOps <noreply@clinicops.local>')
SECURITY_ALERT_EMAILS = [
    email.strip()
    for email in os.environ.get('SECURITY_ALERT_EMAILS', '').split(',')
    if email.strip()
]
PLATFORM_ALERT_EMAILS = [
    email.strip()
    for email in os.environ.get('PLATFORM_ALERT_EMAILS', '').split(',')
    if email.strip()
]
SUPPORT_ALERT_EMAILS = [
    email.strip()
    for email in os.environ.get('SUPPORT_ALERT_EMAILS', '').split(',')
    if email.strip()
]
SECURITY_ALERT_COOLDOWN_MINUTES = int(os.environ.get('SECURITY_ALERT_COOLDOWN_MINUTES', '30'))
RESEND_API_KEY = os.environ.get('RESEND_API_KEY', '')
PUBLIC_BRAND_NAME = os.environ.get('PUBLIC_BRAND_NAME', 'ClinicOps')
PUBLIC_BRAND_COLOR = os.environ.get('PUBLIC_BRAND_COLOR', '#00488a')
PUBLIC_LOGO_URL = os.environ.get('PUBLIC_LOGO_URL', '')
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET', '')
GOOGLE_OAUTH_ENABLED = bool(GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET)
TWO_FACTOR_SUPERUSERS_REQUIRED = os.environ.get('TWO_FACTOR_SUPERUSERS_REQUIRED', 'true').lower() == 'true'
TWO_FACTOR_ALLOW_CLINIC_ADMINS = os.environ.get('TWO_FACTOR_ALLOW_CLINIC_ADMINS', 'true').lower() == 'true'
TWO_FACTOR_RECOVERY_CODE_COUNT = int(os.environ.get('TWO_FACTOR_RECOVERY_CODE_COUNT', '10'))
OTP_TOTP_ISSUER = PUBLIC_BRAND_NAME
OTP_TOTP_THROTTLE_FACTOR = int(os.environ.get('OTP_TOTP_THROTTLE_FACTOR', '1'))

_secured_keys = os.environ.get('SECURED_FIELDS_KEY')
if _secured_keys:
    if ',' in _secured_keys:
        SECURED_FIELDS_KEY = [k.strip() for k in _secured_keys.split(',') if k.strip()]
    else:
        SECURED_FIELDS_KEY = _secured_keys.strip()
else:
    SECURED_FIELDS_KEY = DEFAULT_SECURED_FIELDS_KEY

SECURED_FIELDS_HASH_SALT = os.environ.get('SECURED_FIELDS_HASH_SALT', DEFAULT_SECURED_FIELDS_HASH_SALT)

APPOINTMENT_SLOT_MINUTES = int(os.environ.get('APPOINTMENT_SLOT_MINUTES', '30'))
APPOINTMENT_DAY_START = int(os.environ.get('APPOINTMENT_DAY_START', '9'))
APPOINTMENT_DAY_END = int(os.environ.get('APPOINTMENT_DAY_END', '17'))
APPOINTMENT_DAYS_AHEAD = int(os.environ.get('APPOINTMENT_DAYS_AHEAD', '7'))
SEND_BOOKING_CONFIRMATION = os.environ.get('SEND_BOOKING_CONFIRMATION', 'true').lower() == 'true'

PAYPAL_ENV = os.environ.get('PAYPAL_ENV', 'sandbox')
PAYPAL_CLIENT_ID = os.environ.get('PAYPAL_CLIENT_ID', '')
PAYPAL_SECRET = os.environ.get('PAYPAL_SECRET', '')
PAYPAL_WEBHOOK_ID = os.environ.get('PAYPAL_WEBHOOK_ID', '')
PAYPAL_VERIFY_WEBHOOK = os.environ.get('PAYPAL_VERIFY_WEBHOOK', 'false').lower() == 'true'
PAYPAL_PRODUCT_ID = os.environ.get('PAYPAL_PRODUCT_ID', '')
PAYPAL_SDK_URL = (
    'https://www.sandbox.paypal.com/sdk/js'
    if PAYPAL_ENV == 'sandbox'
    else 'https://www.paypal.com/sdk/js'
)
PAYPAL_API_BASE = (
    'https://api-m.sandbox.paypal.com'
    if PAYPAL_ENV == 'sandbox'
    else 'https://api-m.paypal.com'
)
PAYPAL_SSL_VERIFY = os.environ.get('PAYPAL_SSL_VERIFY', 'true').lower() == 'true'
PAYPAL_CA_BUNDLE = os.environ.get('PAYPAL_CA_BUNDLE', '')
ENFORCE_SUBSCRIPTION = os.environ.get('ENFORCE_SUBSCRIPTION', 'false').lower() == 'true'

# Google social sign-in stays in "existing account only" mode for MVP.
SOCIALACCOUNT_ADAPTER = 'core.social_auth.ClinicSocialAccountAdapter'
SOCIALACCOUNT_AUTO_SIGNUP = False
SOCIALACCOUNT_LOGIN_ON_GET = False
SOCIALACCOUNT_STORE_TOKENS = False
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'EMAIL_AUTHENTICATION': True,
        'EMAIL_AUTHENTICATION_AUTO_CONNECT': True,
        'VERIFIED_EMAIL': True,
        'APPS': [
            {
                'client_id': GOOGLE_CLIENT_ID,
                'secret': GOOGLE_CLIENT_SECRET,
                'key': '',
                'settings': {
                    'scope': ['profile', 'email'],
                    'auth_params': {'access_type': 'online'},
                },
            }
        ]
        if GOOGLE_OAUTH_ENABLED
        else [],
    }
}

Q_CLUSTER = {
    'name': 'clinicops',
    'orm': 'default',
    'workers': 4,
    'timeout': 60,
    'retry': 120,
    'queue_limit': 50,
    'bulk': 10,
}

X_FRAME_OPTIONS = 'DENY'
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
SECURE_CROSS_ORIGIN_RESOURCE_POLICY = 'same-origin'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'core': {
            'handlers': ['console'],
            'level': os.environ.get('CORE_LOG_LEVEL', 'INFO'),
        },
    },
}
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
