from django.urls import path

from . import views

urlpatterns = [
    path('', views.post_login_redirect, name='home'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('calendar/', views.calendar_view, name='calendar'),
    path('staff/appointments/', views.staff_appointments, name='staff-appointments'),
    path('staff/appointments/new/', views.staff_appointment_create, name='staff-appointment-create'),
    path('staff/appointments/<int:appointment_id>/', views.staff_appointment_edit, name='staff-appointment-edit'),
    path('staff/appointments/<int:appointment_id>/history/', views.staff_appointment_history, name='staff-appointment-history'),
    path('staff/patients/', views.staff_patients, name='staff-patients'),
    path('staff/patients/<int:patient_id>/', views.staff_patient_edit, name='staff-patient-edit'),
    path('staff/members/', views.staff_members, name='staff-members'),
    path('staff/members/new/', views.staff_member_create, name='staff-member-create'),
    path('staff/members/<int:staff_id>/', views.staff_member_edit, name='staff-member-edit'),
    path('staff/services/', views.appointment_types, name='appointment-types'),
    path('staff/services/new/', views.appointment_type_create, name='appointment-type-create'),
    path('staff/services/<int:type_id>/', views.appointment_type_edit, name='appointment-type-edit'),
    path('clinic/<int:clinic_id>/', views.clinic_booking, name='clinic-booking'),
    path('clinic/<int:clinic_id>/patient-signup/', views.patient_signup, name='patient-signup'),
    path('clinic/<slug:clinic_slug>/', views.clinic_booking_slug, name='clinic-booking-slug'),
    path('clinic/<slug:clinic_slug>/patient-signup/', views.patient_signup_slug, name='patient-signup-slug'),
    path('signup/', views.clinic_signup, name='clinic-signup'),
    path('signup/activate/', views.signup_activate, name='signup-activate'),
    path('verify-email/<uidb64>/<token>/', views.verify_email, name='verify-email'),
    path('resend-verification/', views.resend_verification, name='resend-verification'),
    path('accounts/2fa/setup/', views.two_factor_setup_view, name='two-factor-setup'),
    path('accounts/2fa/verify/', views.two_factor_verify_view, name='two-factor-verify'),
    path('accounts/2fa/recovery-codes/', views.two_factor_recovery_codes_view, name='two-factor-recovery-codes'),
    path('accounts/2fa/recovery-codes/regenerate/', views.two_factor_regenerate_view, name='two-factor-regenerate'),
    path('accounts/2fa/disable/', views.two_factor_disable_view, name='two-factor-disable'),
    path('settings/', views.settings_view, name='settings'),
    path('settings/security-audit/', views.security_audit_view, name='security-audit'),
    path('search/preview/', views.portal_search_preview, name='portal-search-preview'),
    path('search/', views.portal_search, name='portal-search'),
    path('post-login/', views.post_login_redirect, name='post-login'),
    path('appointments/lookup/', views.appointment_lookup, name='appointment-lookup'),
    path('portal/', views.patient_portal, name='patient-portal'),
    path('notifications/', views.notifications_view, name='notifications'),
    path('notifications/<int:notification_id>/open/', views.notification_open, name='notification-open'),
    path('notifications/<int:notification_id>/read/', views.notification_mark_read, name='notification-mark-read'),
    path('notifications/read-all/', views.notifications_mark_all_read, name='notifications-mark-all-read'),
    path('billing/', views.billing_view, name='billing'),
    path('billing/activate/', views.billing_activate, name='billing-activate'),
    path('billing/sync/', views.billing_sync, name='billing-sync'),
    path('webhooks/paypal/', views.paypal_webhook, name='paypal-webhook'),
]
